# Generated by Django 3.0.7 on 2020-06-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Atalho'),
        ),
    ]
