# Generated by Django 3.0.6 on 2020-06-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do aparelho')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('potencia', models.IntegerField(blank=True, null=True, verbose_name='Potencia em watts')),
                ('tempo', models.IntegerField(blank=True, null=True, verbose_name='Tempo sugerido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'aparelho',
                'verbose_name_plural': 'Aparelho',
                'db_table': 'aparelho',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Aparelho_Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'minutos/dia'), (2, 'horas/dia')], default=2, verbose_name='Tempo sugerido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiente_aparelho', to='ambientes.Ambiente', verbose_name='Ambiente')),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparelho_ambiente', to='aparelhos.Aparelho', verbose_name='Aparelho')),
            ],
            options={
                'verbose_name': 'Aparelho e Ambiente',
                'verbose_name_plural': 'Aparelhos e Ambientes',
                'db_table': 'aparelho_ambiente',
                'unique_together': {('aparelho', 'ambiente')},
            },
        ),
    ]
