# Generated by Django 3.0.7 on 2020-06-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_auto_20200615_2126'),
        ('aparelhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparelho',
            options={'ordering': ['name'], 'verbose_name': 'aparelho', 'verbose_name_plural': 'Aparelhos'},
        ),
        migrations.RemoveField(
            model_name='aparelho',
            name='tempo',
        ),
        migrations.AddField(
            model_name='aparelho_ambiente',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='aparelho_ambiente',
            name='tempo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de uso'),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Atalho'),
        ),
        migrations.AlterField(
            model_name='aparelho_ambiente',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ambientes', to='ambientes.Ambiente', verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='aparelho_ambiente',
            name='aparelho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aparelhos', to='aparelhos.Aparelho', verbose_name='Aparelho'),
        ),
        migrations.AlterField(
            model_name='aparelho_ambiente',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'minutos/dia'), (2, 'horas/dia')], default=2),
        ),
    ]
